### ISSUE TITLE
Pause Video when image is out of track

### ISSUE THREAD

**Issue by n1tesh** [robomex/ARKit-2-Image-Tracking-Demo#1]
How to pause the video when image is not been track and then resume after its in frame again.

**Comment by robomex** [comment]
I created a new branch that checks if isNode insideFrustrumOf the camera's POV – but in the current version of ARKit this method is unreliable.  It works quite well sometimes and not at all other times.

I'm guessing there is a cleaner way to check when tracked items enter/leave/re-enter the field of view, but I will have to revisit this at a later date.  

If you come up with a solution please let me know!
